// <auto-generated />
namespace pet_web_shop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _29042024 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_29042024));
        
        string IMigrationMetadata.Id
        {
            get { return "202404291335136_29042024"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
